version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    volumes:
      - ./:/usr/src
    environment:
      NODE_ENV: ${NODE_ENV}
      DOCKER: 'true'